resena_libros/book_manager/urls.py
from django.urls import path
from .views import *

app_name = 'book_manager'

urlpatterns = [
    path('', index_view, name='index'),
    path('login/', login_view, name='login'),
    path('registro/', register_view, name='register'),
    path('salir/', logout_view, name='logout'),
    path('perfil/', edit_profile_view, name='edit_profile'),
    path('generos/', list_genre, name='list_genre'),
    path('generos/<int:pk>/editar/', GenreUpdateView.as_view(), name='update_genre'),
    path('generos/<int:pk>/eliminar/', GenreDeleteView.as_view(), name='delete_genre'),
    path('autores/', list_authors, name='list_author'),
    path('autores/<int:pk>/editar/', AuthorUpdateView.as_view(), name='update_author'),
    path('autores/<int:pk>/eliminar/', AuthorDeleteView.as_view(), name='delete_author'),
    path('libros/nuevo/', BookCreateView.as_view(), name='create_book'),
    path('libros/<int:pk>/', detail_book, name='detail_book'),
    path('libros/<int:pk>/editar/', BookUpdateView.as_view(), name='update_book'),
    path('libros/<int:pk>/eliminar/', BookDeleteView.as_view(), name='delete_book'),
    path('reviews/create/', create_review, name='create_review'),
    path('contacts/', list_contacts, name='list_contacts'),
]

resena_libros/resena_libros/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_manager.urls', namespace='book_manager')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resena_libros/book_manager/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class User(AbstractUser):
    USER_TYPE_CHOICES = (
        (0, 'admin'),
        (1, 'lector'),
    )
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=1)

    @property
    def is_admin(self):
        return True if self.user_type == 0 else False

    @property
    def is_reader(self):
        return True if self.user_type == 1 else False


class Genre(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    publication_year = models.PositiveIntegerField()
    cover = models.ImageField(upload_to='covers/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    @property
    def get_rating_rounded(self):
        reviews = Review.objects.filter(book=self)
        if reviews:
            rating = round(sum([review.rating for review in reviews]) / len(reviews))
        else:
            rating = 0
        return rating

    def get_reviews(self):
        return Review.objects.filter(book=self)

    @property
    def get_reviews_count(self):
        return Review.objects.filter(book=self).count()


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.TextField()
    rating = models.PositiveIntegerField(validators=[
            MinValueValidator(1),
            MaxValueValidator(5)
        ])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.book.title} - {self.user.username}"


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f'{self.name} - {self.created_at}'

resena_libros/book_manager/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class RegisterForm(forms.Form):
    f_name = forms.CharField(max_length=50)
    l_name = forms.CharField(max_length=50)
    email = forms.EmailField()
    username = forms.CharField(max_length=20)
    password_repeat = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    
    def clean_password(self):
        password = self.cleaned_data['password']
        print(self.cleaned_data)
        password_repeat = self.cleaned_data['password_repeat']
        if len(password) < 8:
            raise forms.ValidationError('La contraseña debe tener al menos 8 caracteres.')
        if password != password_repeat:
            raise forms.ValidationError('Las contraseñas no coinciden.')
        return password

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username','first_name', 'last_name', 'user_type']

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

class ReviewForm(ModelForm):
    STAR_CHOICES = (
    (1, '🫥'),
    (2, '🫥😑'),
    (3, '🫥😑😊'),
    (4, '🫥😑😊😍'),
    (5, '🫥😑😊😍🤩'),
)
    rating = forms.ChoiceField(choices=STAR_CHOICES, label='Rating')
    class Meta:
        model = Review
        fields = '__all__'

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

class GenreForm(ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'

class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

resena_libros/book_manager/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User, Genre, Author, Book, Review, Contact
from .forms import RegisterForm, UserUpdateForm, GenreForm, AuthorForm, ReviewForm, ContactForm
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.db.models import Q

# Create your views here.
def index_view(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, 'Mensaje enviado exitosamente.')
        else:
            for field, errors in contact_form.errors.items():
                for error in errors:
                    messages.error(request, f'{field}: {error}')
    search_term = request.GET.get('search')
    if search_term:
        q = Q(title__icontains=search_term) | Q(description__icontains=search_term) | Q(publication_year__icontains=search_term) | Q(author__name__icontains=search_term) | Q(genre__name__icontains=search_term)
        books = Book.objects.filter(q).order_by('title')
    else:
        books = Book.objects.all().order_by('title')
    contact_form = ContactForm()
    return render(request, 'index.html', {'pagetitle': 'Home', 'books': books, 'contact_form': contact_form, 'search_term': search_term})

def login_view(request):
    if request.user.is_authenticated:
        return redirect('book_manager:index')
    if request.method == 'POST':
        username_or_email = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username_or_email, email=username_or_email, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, f'Bienvenido {user.first_name}!')
            return redirect('book_manager:index')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos')
    form = AuthenticationForm()
    return render(request, 'login.html', {'form': form, 'pagetitle': 'Iniciar sesión'})     

def register_view(request):
    if request.user.is_authenticated:
        return redirect('book_manager:index')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        try:
            if form.is_valid():
                data = form.cleaned_data
                user = User.objects.create_user(username=data['username'], email=data['email'], password=data['password'], first_name=data['f_name'], last_name=data['l_name'])
                messages.success(request, 'Usuario creado exitosamente.')
                return redirect('book_manager:login')
        except ValidationError as e:
            for message in e.messages:
                messages.error(request, message)
            return redirect('book_manager:register')
    form = RegisterForm()
    return render(request, 'register.html', {'form':form, 'pagetitle':'Registro'})

def logout_view(request):
    logout(request)
    messages.success(request, 'Sesión cerrada exitosamente.')
    return redirect('book_manager:index')


@login_required
def edit_profile_view(request):
    password_form = PasswordChangeForm(request.user, request.POST or None)
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        if 'update_profile' in request.POST and user_form.is_valid():
            user_form.save()
            request.user = User.objects.get(id=request.user.id)
            messages.success(request, 'Perfil actualizado exitosamente.')
            return redirect('book_manager:index')
        elif 'change_password' in request.POST:
            if password_form.is_valid():
                password_form.save()
                update_session_auth_hash(request, password_form.user) 
                messages.success(request, 'Contraseña actualizada exitosamente.')
                return redirect('book_manager:index')
            else:
                #add form errors to messages
                for field, errors in password_form.errors.items():
                    for error in errors:
                        messages.error(request, f'{field}: {error}')
    user_form = UserUpdateForm(instance=request.user)

    return render(request, 'profile.html', {
        'pagetitle':'Perfil', 
        'user_form': user_form, 
        'password_form': password_form, 
    })
#GENRES
@login_required
def list_genre(request):
    if request.method == 'POST':
        form = GenreForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Género creado exitosamente.')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'{field}: {error}')
    genres = Genre.objects.all().order_by('name')
    form = GenreForm()
    num_genres = genres.count()
    return render(request, 'genre/list.html', {'genres': genres, 'pagetitle': 'Géneros', 'num_genres': num_genres, 'form': form})

class GenreDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Genre
    success_url = '/generos/'
    template_name = 'layouts/confirm_delete.html'
    context_object_name = 'genre'
    success_message = 'Género eliminado exitosamente.'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagetitle'] = 'Eliminar género'
        return context

class GenreUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Genre
    fields = ['name']
    template_name = 'genre/update.html'
    success_url = '/generos/'
    success_message = 'Género actualizado exitosamente.'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagetitle'] = 'Actualizar género'
        return context
#AUTHORS
@login_required
def list_authors(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Autor creado exitosamente.')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'{field}: {error}')
    authors = Author.objects.all().order_by('name')
    form = AuthorForm()
    author_count = authors.count()
    return render(request, 'author/list.html', {'authors': authors, 'pagetitle': 'Autores', 'author_count': author_count, 'form': form})

class AuthorDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Author
    success_url = '/autores/'
    template_name = 'layouts/confirm_delete.html'
    context_object_name = 'author'
    success_message = 'Autor eliminado exitosamente.'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagetitle'] = 'Eliminar Autor'
        return context

class AuthorUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Author
    fields = ['name']
    template_name = 'author/update.html'
    success_url = '/autores/'
    success_message = 'Autor actualizado exitosamente.'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagetitle'] = 'Actualizar autor'
        return context

#BOOKS

class BookCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Book
    fields = ['title', 'description', 'publication_year', 'cover', 'author', 'genre']
    template_name = 'book/create.html'
    success_url = '/'
    success_message = 'Libro creado exitosamente.'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagetitle'] = 'Crear libro'
        return context

    def form_invalid(self, form):
        response = super().form_invalid(form)
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f'{field}: {error}')
        return response

class BookUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Book
    fields = ['title', 'description', 'publication_year', 'cover', 'author', 'genre']
    template_name = 'book/update.html'
    success_url = '/'
    success_message = 'Libro actualizado exitosamente.'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagetitle'] = 'Actualizar libro'
        return context

    def form_invalid(self, form):
        response = super().form_invalid(form)
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f'{field}: {error}')
        return response
    
class BookDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Book
    success_url = '/'
    template_name = 'layouts/confirm_delete.html'
    context_object_name = 'book'
    success_message = 'Libro eliminado exitosamente.'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagetitle'] = 'Eliminar libro'
        return context

def detail_book(request, pk):
    book = Book.objects.get(pk=pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        #add user and book to form
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.book = book
            obj.save()

resena_libros/book_manager/templates/book/create.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block title %}{{pagetitle}}{% endblock %}
{% block content %}
<section class="user-profile section login-container mt-5">
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user card border-black py-4">
						<h2 class="text-center">Nuevo Libro</h2>
						<p class="text-center">Ingresa los datos para el nuevo libro</p>
					</div>
					<!-- Dashboard Links -->
				</div>
			</div>
			<div class="col-lg-9">
				<div class="row">
                    <form method="post" enctype="multipart/form-data">
						<div class="widget personal-info">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group mb-3">
                                            <label for="book_title">Titulo</label>
                                            {% render_field form.title class+="form-control" id="book_title" %}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="book_author">Autor</label>
                                            {% render_field form.author class+="form-select" id="book_author" %}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="book_genre">Genero</label>
                                            {% render_field form.genre class+="form-select" id="book_genre" %}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="book_pubyear">Año de Publicación</label>
                                            {% render_field form.publication_year class+="form-control" id="book_pubyear" %}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="book_cover">Caratula</label>
                                            {% render_field form.cover class+="form-control" id="book_cover" %}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="book_description">Descripción</label>
                                            {% render_field form.description class+="form-control" id="book_description" %}
                                        </div>
                                    </div>
                                </div>    
								{% csrf_token %}
								<!-- First Name -->
                                <div class="form-group mt-3">
								<button class="btn btn-dark">Guardar libro</button>
                                </div>
                            </form>
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

resena_libros/book_manager/templates/book/show.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block title %}{{pagetitle}}{% endblock %}
{% block content %}
<section class="user-profile section login-container my-5">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user card border-black p-2">
                        <div class="card card-book h-100">
                            <img class="card-img-top" src="{{book.cover.url}}" alt="{{ book.title}}" />
                        </div>
						<h2 class="text-center">{{ book.title }}</h2>
						<p class="text-center fw-bold">{{ book.author.name }}</p>
						<p class="text-center">{{ book.genre.name }}</p>
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            <div class="bi-star{% if book.get_rating_rounded >= 1 %}-fill{% endif %}"></div>
                            <div class="bi-star{% if book.get_rating_rounded >= 2 %}-fill{% endif %}"></div>
                            <div class="bi-star{% if book.get_rating_rounded >= 3 %}-fill{% endif %}"></div>
                            <div class="bi-star{% if book.get_rating_rounded >= 4 %}-fill{% endif %}"></div>
                            <div class="bi-star{% if book.get_rating_rounded >= 5 %}-fill{% endif %}"></div>
                        </div>
                        <p class="text-center p-2">{{ book.description }}</p>
                        {% if user.is_admin %}
                        <div class="text-center">
                            <a href="{% url 'book_manager:update_book' book.id %}" class="btn btn-dark">Editar</a>
                            <a href="{% url 'book_manager:delete_book' book.id %}" class="btn btn-danger">Eliminar</a>
                        </div>
                        {% endif %}
					</div>
				</div>
			</div>
			<div class="col-lg-8">
                {% for review in reviews %}
                <div class="card mb-3">
                    <div class="card-header">
                      {{ review.user.username}}
                    </div>
                    <div class="card-body">
                      <p class="card-text">{{ review.comment }}</p>
                      <div class="d-flex justify-content-start small text-warning mb-2">
                        <div class="bi-star{% if review.rating >= 1 %}-fill{% endif %}"></div>
                        <div class="bi-star{% if review.rating >= 2 %}-fill{% endif %}"></div>
                        <div class="bi-star{% if review.rating >= 3 %}-fill{% endif %}"></div>
                        <div class="bi-star{% if review.rating >= 4 %}-fill{% endif %}"></div>
                        <div class="bi-star{% if review.rating >= 5 %}-fill{% endif %}"></div>
                    </div>
                    </div>
                  </div>
                {% endfor %}
                {% if not reviews %}
                <div class="alert alert-warning" role="alert">
                    El libro aun no tiene reseñas
                  </div>
                {% endif %}
                {% if user.is_authenticated %}
                <div class="card mb-4">
                    <div class="card-header">
                      ✒️ Agregar Review
                    </div>
                    <form method="post">
                    <div class="card-body">
                        <div class="form-group mb-3">
                            <label for="review_comment">Comentario</label>
                            {% render_field review_form.comment class+="form-control" id="review_comment" %}
                        </div>
                        <div class="form-group mb-3">
                            <label for="review_rating">Rating</label>
                            {% render_field review_form.rating class+="form-select" id="review_rating" %}
                        </div>
                      {% csrf_token %}
                      <button class="btn btn-dark">Agregar Review</button>
                    </div>
                    </form>
                  </div>
                {% endif %}
			</div>
		</div>
	</div>
</section>
{% endblock %}

resena_libros/book_manager/templates/book/update.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block title %}{{pagetitle}}{% endblock %}
{% block content %}
<section class="user-profile section login-container mt-5">
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user card border-black py-4">
						<h2 class="text-center">Actualizar Libro</h2>
						<p class="text-center">Puedes cambiar los datos para el nuevo libro</p>
					</div>
					<!-- Dashboard Links -->
				</div>
			</div>
			<div class="col-lg-9">
				<div class="row">
                    <form method="post" enctype="multipart/form-data">
						<div class="widget personal-info">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group mb-3">
                                            <label for="book_title">Titulo</label>
                                            {% render_field form.title class+="form-control" id="book_title" %}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="book_author">Autor</label>
                                            {% render_field form.author class+="form-select" id="book_author" %}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="book_genre">Genero</label>
                                            {% render_field form.genre class+="form-select" id="book_genre" %}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="book_pubyear">Año de Publicación</label>
                                            {% render_field form.publication_year class+="form-control" id="book_pubyear" %}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="book_cover">Caratula</label>
                                            {% render_field form.cover class+="form-control" id="book_cover" %}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="book_description">Descripción</label>
                                            {% render_field form.description class+="form-control" id="book_description" %}
                                        </div>
                                    </div>
                                </div>    
								{% csrf_token %}
								<!-- First Name -->
                                <div class="form-group mt-3">
								<button class="btn btn-dark">Guardar libro</button>
                                <!-- Return button -->
                                <a href="{{request.META.HTTP_REFERER}}" class="btn btn-outline-dark">Volver</a>
                                </div>
                            </form>
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}